---
schemas:
  - models/circuit.yml
  - models/dcim.yml
  - models/ipam.yml
  - models/locations.yml
  - models/organizations.yml
  - models/routing.yml
  - models/security.yml
  - models/service.yml
  - models/topology.yml
jinja2_transforms:
  - name: "device_cisco"
    description: "Template to generate startup configuration for Cisco devices"
    query: "device_info"
    template_path: "templates/device_cisco_config.tpl.j2"

  - name: "device_arista"
    description: "Template to generate startup configuration for Arista devices"
    query: "device_info"
    template_path: "templates/device_arista_config.tpl.j2"

  - name: "device_sonic"
    description: "Template to generate startup configuration for Arista devices"
    query: "device_info"
    template_path: "templates/device_sonic_config.tpl.j2"

artifact_definitions:
  - name: "Startup Config for Cisco devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "cisco_devices"
    transformation: "device_cisco"

  - name: "Startup Config for Arista devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "device_arista"

check_definitions:
  - name: "check_device_topology"
    class_name: "InfrahubCheckDeviceTopology"
    file_path: "checks/check_device_topology.py"
  - name: backbone_link_redundancy
    class_name: InfrahubCheckBackboneLinkRedundancy
    file_path: "checks/check_backbone_link_redundancy.py"

generator_definitions:
  - name: create_topology
    file_path: "generators/generate_topology.py"
    targets: all_topologies
    query: generate_topology
    class_name: TopologyGenerator
    parameters:
      name: "name__value"
  - name: create_circuit_endpoints
    file_path: "generators/circuit_endpoints.py"
    targets: provisioning_circuits
    query: circuit_endpoints
    class_name: CircuitGenerator
    parameters:
      circuit_id: "circuit_id__value"
